'use client'

import { useState, useEffect, useRef } from 'react'

interface Message {
  role: 'user' | 'assistant'
  content: string
}

interface OutlineStep {
  step: number
  title: string
  description: string
  priority: 'start here' | 'recommended' | 'advanced'
}

const priorityStyles: Record<string, string> = {
  'start here': 'bg-green-500/20 text-green-400 border border-green-500/30',
  'recommended': 'bg-blue-500/20 text-blue-400 border border-blue-500/30',
  'advanced': 'bg-purple-500/20 text-purple-400 border border-purple-500/30',
}

export default function AITutor() {
  const [outline, setOutline] = useState<OutlineStep[]>([])
  const [outlineLoading, setOutlineLoading] = useState(true)
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [chatLoading, setChatLoading] = useState(false)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    fetch('/api/ai-tutor', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mode: 'outline', messages: [] }),
    })
      .then((r) => r.json())
      .then((data) => {
        if (data.outline) setOutline(data.outline)
      })
      .finally(() => setOutlineLoading(false))
  }, [])

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, chatLoading])

  async function sendMessage() {
    if (!input.trim() || chatLoading) return
    const userMsg: Message = { role: 'user', content: input.trim() }
    const updated = [...messages, userMsg]
    setMessages(updated)
    setInput('')
    setChatLoading(true)

    const res = await fetch('/api/ai-tutor', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mode: 'chat', messages: updated }),
    })
    const data = await res.json()
    if (data.reply) {
      setMessages([...updated, { role: 'assistant', content: data.reply }])
    }
    setChatLoading(false)
  }

  return (
    <div className="space-y-10">

      {/* Personalized Roadmap */}
      <div className="bg-gray-900 border border-green-500/20 rounded-xl p-6">
        <h3 className="text-xl font-bold text-white mb-1">Your Personalized Roadmap</h3>
        <p className="text-gray-400 text-sm mb-6">Generated by AI based on your risk profile and goals</p>

        {outlineLoading ? (
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-16 bg-gray-800 rounded-lg animate-pulse" />
            ))}
          </div>
        ) : (
          <div className="space-y-3">
            {outline.map((step) => (
              <div
                key={step.step}
                className="flex items-start gap-4 bg-gray-800/50 rounded-lg p-4 border border-gray-700/50"
              >
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-500/10 border border-green-500/30 flex items-center justify-center text-green-400 font-bold text-sm">
                  {step.step}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className="text-white font-semibold">{step.title}</span>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium capitalize ${priorityStyles[step.priority] || priorityStyles['recommended']}`}>
                      {step.priority}
                    </span>
                  </div>
                  <p className="text-gray-400 text-sm">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* AI Chat */}
      <div className="bg-gray-900 border border-green-500/20 rounded-xl overflow-hidden">
        <div className="border-b border-gray-800 px-6 py-4">
          <h3 className="text-xl font-bold text-white">Ask Your AI Tutor</h3>
          <p className="text-gray-400 text-sm">Knows your profile — ask anything about investing</p>
        </div>

        {/* Messages */}
        <div className="h-80 overflow-y-auto px-6 py-4 space-y-4">
          {messages.length === 0 && (
            <div className="text-center text-gray-500 text-sm mt-8">
              Ask a question to get started. Your AI tutor already knows your profile.
            </div>
          )}
          {messages.map((msg, i) => (
            <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div
                className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                  msg.role === 'user'
                    ? 'bg-green-500 text-black font-medium rounded-br-sm'
                    : 'bg-gray-800 text-gray-200 rounded-bl-sm'
                }`}
              >
                    <span dangerouslySetInnerHTML={{ __html: msg.content
                    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                    .replace(/\n- /g, '<br>• ')
                    .replace(/\n/g, '<br>')
                    }} />
              </div>
            </div>
          ))}
          {chatLoading && (
            <div className="flex justify-start">
              <div className="bg-gray-800 rounded-2xl rounded-bl-sm px-4 py-3">
                <div className="flex gap-1">
                  <span className="w-2 h-2 bg-gray-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                  <span className="w-2 h-2 bg-gray-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                  <span className="w-2 h-2 bg-gray-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                </div>
              </div>
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        {/* Input */}
        <div className="border-t border-gray-800 px-4 py-3 flex gap-3">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && sendMessage()}
            placeholder="e.g. What's a good ETF for my risk profile?"
            className="flex-1 bg-gray-800 text-white text-sm rounded-lg px-4 py-2.5 outline-none border border-gray-700 focus:border-green-500/50 placeholder-gray-500 transition"
          />
          <button
            onClick={sendMessage}
            disabled={chatLoading || !input.trim()}
            className="bg-green-500 text-black font-semibold text-sm px-4 py-2.5 rounded-lg hover:bg-green-400 transition disabled:opacity-40 disabled:cursor-not-allowed"
          >
            Send
          </button>
        </div>
      </div>

    </div>
  )
}